const $=id=>document.getElementById(id);let selected=new Set(),timer=null;
const symbols=[...new Set([...(window.DATA_SYMBOLS||[]),...(window.DATA_INDICES||[])])],nifty50=window.DATA_NIFTY50||[],nifty100=window.DATA_NIFTY100||[],indices=window.DATA_INDICES||[];
function today(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function dateOffset(days){const d=new Date();d.setDate(d.getDate()+days);return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(d)}
function choose(list){selected=new Set(list);renderSymbols();renderChips();updateSummary()}
function renderSymbols(){const q=($('symbolSearch').value||'').trim().toUpperCase();const visible=symbols.filter(s=>!q||s.toUpperCase().includes(q));$('symbolList').innerHTML=visible.map(s=>`<label class="symbol-option ${selected.has(s)?'selected':''}"><input type="checkbox" data-s="${s}" ${selected.has(s)?'checked':''}> <span>${s}</span></label>`).join('')||'<div class="empty-state">No matching instruments.</div>';$('symbolList').querySelectorAll('input').forEach(i=>i.onchange=()=>{i.checked?selected.add(i.dataset.s):selected.delete(i.dataset.s);renderSymbols();renderChips();updateSummary()})}
function renderChips(){$('chips').innerHTML=[...selected].slice(0,30).map(s=>`<span class="chip">${s}<button data-s="${s}">×</button></span>`).join('')+(selected.size>30?`<span class="chip">+${selected.size-30} more</span>`:'')||'<span class="muted">No instruments selected yet. Choose a group above or select individual instruments.</span>';$('chips').querySelectorAll('button').forEach(b=>b.onclick=()=>{selected.delete(b.dataset.s);renderSymbols();renderChips();updateSummary()})}
function updateSummary(){const f=$('from').value,t=$('to').value||f;$('selectedCount').textContent=selected.size;$('selectionHint').textContent=`${selected.size} selected`;$('summaryInterval').textContent=$('interval').value;$('summaryDates').textContent=f?(f===t?f:`${f} → ${t}`):'—';$('summaryRange').textContent=f?(f===t?(f===today()?'Today':f):'Custom'):'—'}
function renderCoverage(c){const rows=Object.entries(c);$('coverage').innerHTML=rows.length?rows.map(([i,v])=>`<div class="coverage-row"><b>${i}</b><span>${v.min_date||'—'} → ${v.max_date||'—'}</span><strong>${Number(v.rows||0).toLocaleString('en-IN')} rows</strong></div>`).join(''):'<div class="empty-state">No local coverage reported yet.</div>'}
async function status(){try{const r=await fetch('/api/data/status?_='+Date.now(),{cache:'no-store'}),d=await r.json();const j=d.job||{};const running=!!j.running,done=Number(j.done||0),total=Number(j.total||0),pct=total?Math.min(100,done/total*100):0;const state=running?'RUNNING':(j.status||'IDLE').toUpperCase();$('fetchStatus').textContent=state;$('summaryStatus').textContent=state;$('progressText').textContent=j.status||'Waiting';$('jobInstrument').textContent=j.status?.startsWith('Fetching ')?j.status.replace(/^Fetching /,'').replace(/ \(.*$/,''):'—';$('jobProgress').textContent=`${done} / ${total}`;$('jobRows').textContent=Number(j.rows||0).toLocaleString('en-IN');$('jobErrors').textContent=(j.errors||[]).length;$('bar').style.width=pct+'%';$('progressPercent').textContent=Math.round(pct)+'%';$('warning').textContent=j.warning||'';renderCoverage(d.coverage||{});if(running){clearTimeout(timer);timer=setTimeout(status,1000)}}catch(e){$('fetchStatus').textContent='ERROR';$('summaryStatus').textContent='ERROR'}}
function setRange(kind){document.querySelectorAll('.preset-btn').forEach(b=>b.classList.toggle('active',b.dataset.range===kind));const t=today();if(kind==='today'){$('from').value=t;$('to').value=t}else if(kind==='yesterday'){$('from').value=dateOffset(-1);$('to').value=dateOffset(-1)}else{const n=Number(kind);$('from').value=dateOffset(-(n-1));$('to').value=t}updateSummary()}
$('qN50').onclick=()=>choose(nifty50);$('qN100').onclick=()=>choose(nifty100);$('qIndex').onclick=()=>choose(indices);$('qAll').onclick=()=>choose(symbols);$('qClear').onclick=()=>choose([]);$('refreshCoverage').onclick=status;$('symbolSearch').oninput=renderSymbols;$('interval').onchange=updateSummary;$('from').onchange=()=>{document.querySelectorAll('.preset-btn').forEach(b=>b.classList.remove('active'));updateSummary()};$('to').onchange=()=>{document.querySelectorAll('.preset-btn').forEach(b=>b.classList.remove('active'));updateSummary()};document.querySelectorAll('.preset-btn').forEach(b=>b.onclick=()=>setRange(b.dataset.range));
$('fetch').onclick=async()=>{const f=$('from').value,t=$('to').value||f;if(!selected.size){alert('Select at least one instrument first.');return}if(f&&t&&f>t){alert('FROM date cannot be after TO date.');return}const btn=$('fetch');btn.disabled=true;btn.textContent='Starting…';try{const r=await fetch('/api/data/fetch',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({symbols:[...selected],interval:$('interval').value,date_from:f,date_to:t})});const d=await r.json();if(!r.ok||!d.success){alert(d.error||'Unable to start fetch');return}await status()}catch(e){alert('Unable to start the fetch job. Please check the server.')}finally{btn.disabled=false;btn.textContent='Fetch & Save Data'}};
$('from').value=today();$('to').value=today();document.querySelector('[data-range="today"]').classList.add('active');setInterval(()=>{$('clock').textContent=new Date().toLocaleTimeString('en-IN',{timeZone:'Asia/Kolkata',hour12:true})},1000);$('clock').textContent=new Date().toLocaleTimeString('en-IN',{timeZone:'Asia/Kolkata',hour12:true});choose([]);updateSummary();status();
